spring.application.name=pulsegrid-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pulsegrid
spring.datasource.username=pulsegrid
spring.datasource.password=pulsegrid

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true